# SPDX-FileCopyrightText: 2024 Deutsche Telekom AG
#
# SPDX-License-Identifier: CC0-1.0    

# See https://reuse.software/spec-3.2/#reusetoml for specification
version = 1

# All UI files from the Qt Designer:
[[annotations]]
path = ["**/*.ui"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Deutsche Telekom Technik GmbH <f.vonstudsinske@telekom.de>"
SPDX-License-Identifier = "GPL-3.0-only"

# All QGIS Print Layouts *.qpt:
[[annotations]]
path = ["**/*.qpt"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Deutsche Telekom Technik GmbH <f.vonstudsinske@telekom.de>"
SPDX-License-Identifier = "GPL-3.0-only"

# No special copyrights, e.g. screenshots or config files:
[[annotations]]
path = ["**/.gitignore", "docs/ui-file-validation-ignore-name-check.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "GPL-3.0-only"

# All i18n translation files:
[[annotations]]
path = ["i18n/*.qm", "i18n/*.ts"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Deutsche Telekom Technik GmbH <f.vonstudsinske@telekom.de>"
SPDX-License-Identifier = "GPL-3.0-only"

